import {
  ArrowLeft,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleX,
  CloudDownload,
  CloudUpload,
  Database,
  Download,
  ExternalLink,
  FileText,
  Image as ImageIcon,
  Images,
  Inbox,
  Info,
  LoaderCircle,
  LocateFixed,
  Map,
  MapPin,
  Maximize2,
  MessageCircle,
  Moon,
  Receipt,
  RotateCcw,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Smartphone,
  Sun,
  Table2,
  Trash2,
  TriangleAlert,
  Video,
  WifiOff,
  X,
  type LucideProps,
} from 'lucide-react';
import type { ComponentType } from 'react';

const icons = {
  arrowLeft: ArrowLeft,
  camera: Camera,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circleAlert: CircleAlert,
  circleCheck: CircleCheck,
  circleX: CircleX,
  cloudDownload: CloudDownload,
  cloudUpload: CloudUpload,
  database: Database,
  download: Download,
  expand: Maximize2,
  externalLink: ExternalLink,
  file: FileText,
  image: ImageIcon,
  images: Images,
  inbox: Inbox,
  info: Info,
  loader: LoaderCircle,
  locate: LocateFixed,
  map: Map,
  mapPin: MapPin,
  message: MessageCircle,
  moon: Moon,
  receipt: Receipt,
  refresh: RotateCcw,
  search: Search,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  smartphone: Smartphone,
  sun: Sun,
  table: Table2,
  trash: Trash2,
  triangleAlert: TriangleAlert,
  video: Video,
  wifiOff: WifiOff,
  x: X,
} satisfies Record<string, ComponentType<LucideProps>>;

export type IconName = keyof typeof icons;

export default function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" {...props} />;
}
