import {
  ArrowLeft,
  ArrowRight,
  BriefcaseBusiness,
  CalendarDays,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleX,
  CloudDownload,
  CloudUpload,
  Database,
  Download,
  ExternalLink,
  FileText,
  Flame,
  FolderOpen,
  GripVertical,
  HeartPulse,
  Image as ImageIcon,
  Images,
  Inbox,
  Info,
  Landmark,
  ListChecks,
  LoaderCircle,
  LocateFixed,
  Map,
  MapPin,
  Maximize2,
  MessageCircle,
  Moon,
  PanelTop,
  Receipt,
  RotateCcw,
  Search,
  Send,
  Server,
  Settings,
  ShieldCheck,
  ShieldUser,
  Smartphone,
  Sparkles,
  Sun,
  Table2,
  Trash2,
  TriangleAlert,
  UsersRound,
  Video,
  Wifi,
  WifiOff,
  X,
  type LucideProps,
} from 'lucide-react';
import type { ComponentType } from 'react';

const icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  briefcase: BriefcaseBusiness,
  calendar: CalendarDays,
  camera: Camera,
  check: Check,
  checkDouble: CheckCheck,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circleAlert: CircleAlert,
  circleCheck: CircleCheck,
  circleX: CircleX,
  cloudDownload: CloudDownload,
  cloudUpload: CloudUpload,
  database: Database,
  download: Download,
  expand: Maximize2,
  externalLink: ExternalLink,
  file: FileText,
  flame: Flame,
  folder: FolderOpen,
  grip: GripVertical,
  heart: HeartPulse,
  image: ImageIcon,
  images: Images,
  inbox: Inbox,
  info: Info,
  landmark: Landmark,
  list: ListChecks,
  loader: LoaderCircle,
  locate: LocateFixed,
  map: Map,
  mapPin: MapPin,
  message: MessageCircle,
  moon: Moon,
  panel: PanelTop,
  receipt: Receipt,
  refresh: RotateCcw,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  shield: ShieldCheck,
  shieldUser: ShieldUser,
  smartphone: Smartphone,
  sparkles: Sparkles,
  sun: Sun,
  table: Table2,
  trash: Trash2,
  triangleAlert: TriangleAlert,
  users: UsersRound,
  video: Video,
  wifi: Wifi,
  wifiOff: WifiOff,
  x: X,
} satisfies Record<string, ComponentType<LucideProps>>;

export type IconName = keyof typeof icons;

export default function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" {...props} />;
}

/** Ikon kategori pada kartu menu. */
export const categoryIcons = {
  shield: ShieldCheck,
  landmark: Landmark,
  heart: HeartPulse,
  flame: Flame,
  users: UsersRound,
  briefcase: BriefcaseBusiness,
} satisfies Record<string, ComponentType<LucideProps>>;
